apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  labels:
    app: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        - name: drupal-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: drupal-mysql-pvc
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: drupal-database

      volumes:
        - name: drupal-mysql-pvc
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
