apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-phpfpm
  name: nginx-phpfpm
spec:
  containers:
    - image: nginx:latest
      name: nginx-phpfpm
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
        - mountPath: /shared
          name: shared-files
    - image: php:8.1-fpm-alpine
      name: php-fpm-container
      volumeMounts:
        - mountPath: /shared
          name: shared-files

  volumes:
    - name: shared-files
      emptyDir:
        sizeLimit: 500Mi- name: nginx-config-volume
    - name: nginx-config-volume
      configMap:
        name: nginx-config
     
