apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redisslave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redisslave
  template:
    metadata:
      labels:
        app: redisslave
    spec:
      containers:
        - name: slave-redis-devops
          image: gcr.io/google_samples/gb-redisslave:v3
          ports:
            - containerPort: 6379
          env:
            - name: GET_HOSTS_FROM
              value: dns
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
